import json
import os
from django import template
from django.conf import settings
from django.utils.safestring import mark_safe
from django.apps import apps

register = template.Library()

VITE_DEV_MODE = getattr(settings, "DJANGO_UMIN_VITE_DEV_MODE", False)
VITE_DEV_SERVER_HOST = getattr(
    settings, "DJANGO_UMIN_VITE_DEV_SERVER_HOST", "localhost"
)
VITE_DEV_SERVER_PORT = getattr(settings, "DJANGO_UMIN_VITE_DEV_SERVER_PORT", 5173)
VITE_DEV_SERVER_PROTOCOL = getattr(
    settings, "DJANGO_UMIN_VITE_DEV_SERVER_PROTOCOL", "http"
)
VITE_DEV_SERVER_URL = getattr(settings, "DJANGO_UMIN_VITE_DEV_SERVER_URL", None)


@register.simple_tag
def vite_asset(path, app):
    """
    Generates <script> or <link> tags for a Vite asset.
    Handles both development and production modes.
    """
    if VITE_DEV_MODE:
        # In development, generate URLs to the project-level Vite dev server
        # Support proxied environments (e.g., GitHub Codespaces) by allowing full URL override
        if VITE_DEV_SERVER_URL:
            # Use explicit dev server URL (e.g., "https://codespace-5173.app.github.dev")
            base_url = VITE_DEV_SERVER_URL.rstrip("/")
        else:
            # Construct from host, port, and protocol (default: http://localhost:5173)
            base_url = f"{VITE_DEV_SERVER_PROTOCOL}://{VITE_DEV_SERVER_HOST}:{VITE_DEV_SERVER_PORT}"

        # The @vite/client script is a special case and is served from the root.
        if path == "@vite/client":
            return mark_safe(f'<script type="module" src="{base_url}/{path}"></script>')

        try:
            app_config = apps.get_app_config(app)
        except LookupError:
            raise RuntimeError(f"Application '{app}' not found in INSTALLED_APPS.")

        # Construct the full path to the asset relative to project root
        # Since Vite root is the project root, we need the full path from project root to the asset
        project_root = str(settings.BASE_DIR)
        app_fe_dir = os.path.join(app_config.path, "fe")

        # Get the relative path from project root to the app's fe directory
        rel_fe_dir = os.path.relpath(app_fe_dir, project_root).replace("\\", "/")

        # Construct the asset path: fe_dir + asset_path
        asset_url_path = f"{rel_fe_dir}/{path}"

        # The Vite dev server has base='/static/', so URLs must start with /static/
        full_asset_url = f"{base_url}/static/{asset_url_path}"

        if full_asset_url.endswith(".js"):
            return mark_safe(f'<script type="module" src="{full_asset_url}"></script>')
        elif full_asset_url.endswith(".css"):
            return mark_safe(f'<link rel="stylesheet" href="{full_asset_url}">')

    # --- Production Mode ---
    # In production, read from the manifest file generated by `vite_build`
    # The manifest path is relative to the app's static directory
    manifest_path = os.path.join(settings.STATIC_ROOT, app, "dist", "manifest.json")

    if not os.path.exists(manifest_path):
        # First, try to find it within the app's static directory if collectstatic hasn't run
        app_static_manifest_path = os.path.join(
            apps.get_app_config(app).path, "static", app, "dist", "manifest.json"
        )
        if not os.path.exists(app_static_manifest_path):
            raise RuntimeError(
                f"Vite manifest not found. Looked in {manifest_path} and {app_static_manifest_path}. Did you run `manage.py vite_build`?"
            )
        manifest_path = app_static_manifest_path

    with open(manifest_path) as f:
        manifest = json.load(f)

    # The manifest keys are relative to the app's `fe` directory, e.g., 'js/main.js'
    # We need to find the right key. The `path` passed in might be 'main.js'.
    manifest_key = None
    for key in manifest:
        if key.endswith(path):
            manifest_key = key
            break

    if not manifest_key:
        raise RuntimeError(f"Asset '{path}' not found in manifest for app '{app}'.")

    asset_info = manifest[manifest_key]
    # The asset URL is relative to the `dist` folder.
    asset_url = os.path.join(settings.STATIC_URL, app, "dist", asset_info["file"])

    if asset_url.endswith(".js"):
        return mark_safe(f'<script type="module" src="{asset_url}"></script>')
    elif asset_url.endswith(".css"):
        return mark_safe(f'<link rel="stylesheet" href="{asset_url}">')
    else:
        return mark_safe(f"<!-- Unsupported asset type for {asset_url} -->")
