import json
import os
from django import template
from django.conf import settings
from django.utils.safestring import mark_safe
from django.apps import apps

register = template.Library()

VITE_DEV_MODE = getattr(settings, "DJANGO_UMIN_VITE_DEV_MODE", False)
VITE_DEV_SERVER_HOST = getattr(
    settings, "DJANGO_UMIN_VITE_DEV_SERVER_HOST", "localhost"
)
VITE_DEV_SERVER_PORT = getattr(settings, "DJANGO_UMIN_VITE_DEV_SERVER_PORT", 5173)


@register.simple_tag
def vite_asset(path, app):
    """
    Generates <script> or <link> tags for a Vite asset.
    Handles both development and production modes.
    """
    if VITE_DEV_MODE:
        # In development, generate URLs to the project-level Vite dev server
        base_url = f"http://{VITE_DEV_SERVER_HOST}:{VITE_DEV_SERVER_PORT}"

        # The @vite/client script is a special case and is served from the root.
        if path == "@vite/client":
            return mark_safe(f'<script type="module" src="{base_url}/{path}"></script>')

        try:
            app_config = apps.get_app_config(app)
        except LookupError:
            raise RuntimeError(f"Application '{app}' not found in INSTALLED_APPS.")

        # Construct the asset path relative to the app's 'fe' directory
        asset_url_path = path

        # The Vite dev server will serve the file from this path, with the base '/static/'
        full_asset_url = f"{base_url}/static/{asset_url_path}"

        if full_asset_url.endswith(".js"):
            return mark_safe(f'<script type="module" src="{full_asset_url}"></script>')
        elif full_asset_url.endswith(".css"):
            return mark_safe(f'<link rel="stylesheet" href="{full_asset_url}">')

    # --- Production Mode ---
    # In production, read from the manifest file generated by `vite_build`
    # The manifest path is relative to the app's static directory
    manifest_path = os.path.join(settings.STATIC_ROOT, app, "dist", "manifest.json")

    if not os.path.exists(manifest_path):
        # First, try to find it within the app's static directory if collectstatic hasn't run
        app_static_manifest_path = os.path.join(
            apps.get_app_config(app).path, "static", app, "dist", "manifest.json"
        )
        if not os.path.exists(app_static_manifest_path):
            raise RuntimeError(
                f"Vite manifest not found. Looked in {manifest_path} and {app_static_manifest_path}. Did you run `manage.py vite_build`?"
            )
        manifest_path = app_static_manifest_path

    with open(manifest_path) as f:
        manifest = json.load(f)

    # The manifest keys are relative to the app's `fe` directory, e.g., 'js/main.js'
    # We need to find the right key. The `path` passed in might be 'main.js'.
    manifest_key = None
    for key in manifest:
        if key.endswith(path):
            manifest_key = key
            break

    if not manifest_key:
        raise RuntimeError(f"Asset '{path}' not found in manifest for app '{app}'.")

    asset_info = manifest[manifest_key]
    # The asset URL is relative to the `dist` folder.
    asset_url = os.path.join(settings.STATIC_URL, app, "dist", asset_info["file"])

    if asset_url.endswith(".js"):
        return mark_safe(f'<script type="module" src="{asset_url}"></script>')
    elif asset_url.endswith(".css"):
        return mark_safe(f'<link rel="stylesheet" href="{asset_url}">')
    else:
        return mark_safe(f"<!-- Unsupported asset type for {asset_url} -->")
