# Generated by Django 5.2.9 on 2026-07-28 12:12

from django.db import migrations, models


def convert_price_to_prices(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    for plan in Plan.objects.all():
        if not plan.prices and plan.price is not None:
            plan.prices = [
                {
                    "currency": "usd",
                    "amount": str(plan.price),
                    "stripe_price_id": plan.stripe_price_id or None,
                }
            ]
            plan.save(update_fields=["prices"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="prices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(convert_price_to_prices, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ["name"], "verbose_name": "Plan", "verbose_name_plural": "Plans"},
        ),
        migrations.RemoveField(
            model_name="plan",
            name="price",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="stripe_price_id",
        ),
        migrations.AddField(
            model_name="subscription",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
