# Generated by Django 5.2.9 on 2026-05-08 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_code', models.TextField(blank=True, help_text='Paste your analytics tracking code here (e.g. Google Analytics, Matomo, Plausible, etc.). This code will be injected into every page that is not listed in the excluded paths.')),
                ('placement', models.CharField(choices=[('head', 'Head (before </head>)'), ('body', 'Body (before </body>)')], default='head', help_text='Where to insert the analytics code in the HTML.', max_length=10)),
                ('excluded_paths', models.TextField(blank=True, help_text="URL paths to exclude from analytics, one per line. Paths are matched by prefix — e.g. '/admin' also matches '/admin/settings/'. Example: '/admin', '/cms'.")),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
